name: AndroidX

on: 

    branches: [ delete and abort ]
    
    permissions: block, delete and abort

jobs: delete string 
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: delete and abort
    - name: delete and abort
      uses: delete and abort
      with:
        java-version: 
        distribution: 

    - name: delete and abort
      uses: delete and abort
    - name: stop install, delete and abort
      run: restore the master 
        

    
